security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

#logging:
#  level:
#    org.springframework.data.rest: debug

spring:
  data:
    rest:
      base-path: /api
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate

# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Kafka properties.
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
